### ISSUE TITLE
While trying to fetch data using Post, Reply is 500

### ISSUE THREAD

**Issue by anpinamthal** [uniubi-uface/athena-java-sdk#1]
Dear Team, when we try to fetch the data using Post Method, we are getting 500 as status. Please guide us how to fetch the data.

We are trying to use a windows service in c# to fetch the data from the Ustar Cloud. 
![UStar](https://user-images.githubusercontent.com/104498099/165496559-9fd375bb-afe6-4d65-af51-93bb8c8f79d5.png)

**Comment by helloichen** [comment]
1. ` https://www.ustar-cloud.com/api/develop/sdk/v1` is different from 'https://www.ustar-cloud.com/api/develop/sdk/v1/'. 
2.  [OpenApi](https://github.com/uniubi-uface/athena-java-sdk/blob/main/docs/UStar%20cloud%20open%20API.md) #1.2 indicates whether encryption is required.
3. Your request header incorrect。[OpenApi](https://github.com/uniubi-uface/athena-java-sdk/blob/main/docs/UStar%20cloud%20open%20API.md) #1.1 . The requirements for request parameters and request headers are described in the table。Those headers are required. You just only `Content-Type` from the image you provided.

**Comment by helloichen** [comment]
> Dear Team, when we try to fetch the data using Post Method, we are getting 500 as status. Please guide us how to fetch the data.
> 
> We are trying to use a windows service in c# to fetch the data from the Ustar Cloud. ![UStar](https://user-images.githubusercontent.com/104498099/165496559-9fd375bb-afe6-4d65-af51-93bb8c8f79d5.png)

**Comment by helloichen** [comment]
> Dear Team, when we try to fetch the data using Post Method, we are getting 500 as status. Please guide us how to fetch the data.
> 
> We are trying to use a windows service in c# to fetch the data from the Ustar Cloud. ![UStar](https://user-images.githubusercontent.com/104498099/165496559-9fd375bb-afe6-4d65-af51-93bb8c8f79d5.png)

1. ` https://www.ustar-cloud.com/api/develop/sdk/v1` is different from 'https://www.ustar-cloud.com/api/develop/sdk/v1/'. 
2.  [OpenApi](https://github.com/uniubi-uface/athena-java-sdk/blob/main/docs/UStar%20cloud%20open%20API.md) #1.2 indicates whether encryption is required.
3. Your request header incorrect。[OpenApi](https://github.com/uniubi-uface/athena-java-sdk/blob/main/docs/UStar%20cloud%20open%20API.md)    `Request Address`. The requirements for request parameters and request headers are described in the table。Those headers are required. You just only `Content-Type` from the image you provided.

**Comment by helloichen** [comment]
1. ` https://www.ustar-cloud.com/api/develop/sdk/v1`  is different from `https://www.ustar-cloud.com/api/develop/sdk/v1/`. 
2.  [OpenApi](https://github.com/uniubi-uface/athena-java-sdk/blob/main/docs/UStar%20cloud%20open%20API.md)  indicates whether encryption is required.
3. Your request header incorrect。OpenApi  Request Address The requirements for request parameters and request headers are described in the table。Those headers are required. You just only `Content-Type` from the image you provided.

**Comment by helloichen** [comment]
> Dear Team, when we try to fetch the data using Post Method, we are getting 500 as status. Please guide us how to fetch the data.
> 
> We are trying to use a windows service in c# to fetch the data from the Ustar Cloud. ![UStar](https://user-images.githubusercontent.com/104498099/165496559-9fd375bb-afe6-4d65-af51-93bb8c8f79d5.png)

We have updated the open API documentation with several error. 
You can try again. Thank you for your feedback. 
Expect feedback again.
